<div class="bbn-flex-height bbn-background bbn-overlay" ref="browser">
  <bbn-gallery :source="source"
               :searchName="searchName" 
               :pageable="pageable"
               :filterable="filterable"
               :limit="limit"
               :zoomable="zoomable"
               :info="info"
               :path-name="pathName"
               :overlay-name="overlayName"
               :overlay="overlay"
               :toolbar="true"
               :uploadable="uploadEnabled"
               :downloadable="downloadEnabled"
               :deletable="removeEnabled"
               @upload="addMedia"
               @download="downloadMedia"
               @delete="removeMedia"
               @selection="selectMedia"
               :buttons-no-text="true"
               :buttonMenu="currentButtonMenu"
               :buttonMenuComponent="buttonMenuComponent"
               :selection="selection"/>
</div>